### ISSUE TITLE
Revert use of custom Bazel for macos_build in CI workflow

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/rules_spm#112]
Remove the use of the custom Bazel in the`macos_build`.

```yaml
    # Remove this when Keith's PR is merged and made available in a Bazel release.
    env:
      USE_BAZEL_VERSION: cgrindel/6.0.0-keith_patch
```

## Background

Error from [GitHub Actions run](https://github.com/cgrindel/rules_spm/runs/4886936718?check_suite_focus=true).

```
ERROR: /private/var/tmp/_bazel_runner/6ba398470370e09a654e1f7bdb97a6ab/external/io_bazel_stardoc/stardoc/BUILD:70:12: Target '@io_bazel_stardoc//stardoc:renderer' depends on toolchain '@local_config_cc//:cc-compiler-darwin', which cannot be found: error loading package '@local_config_cc//': cannot load '@local_config_cc_toolchains//:osx_archs.bzl': no such file'
```

[Keith's PR with fix](https://github.com/bazelbuild/bazel/pull/13529). 
- bazelbuild/bazel#13529

[Chuck's custom Bazel release with Keith's patch](https://github.com/cgrindel/bazel/releases/tag/6.0.0-keith_patch)

Related Issues:
- https://github.com/bazelbuild/bazel/issues/14459
- https://github.com/bazelbuild/bazel/issues/14603
